### ISSUE TITLE
Missing ros_snapshot

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/rosgraph_monitor#13]
#### Behavior
I want to create a rossystem of an existing application.
But the result looks different from the example. 

#### Steps to reproduce this issue
* install [araig_test_stack](https://github.com/ipa-rwu/araig_test_stack) from branch "rwu/test/gazebo_nav_launch"
* First experiment:
  terminal 1:
  ```
  roslaunch turtlebot3_sim_tests gazebo_nav.launch
  ```
  terminal 2:
  ```
  rosrun rosgraph_monitor rossystem_snapshot
  ```
   result:
  [ turtlebot3_sim_tests/resources/turtlebot_nav.rossystem
  ](https://github.com/ipa-rwu/araig_test_stack/blob/095fca1aa9d7ad7babb14a6f4b56a303f5fd77bb/turtlebot3_sim_tests/resources/turtlebot_nav.rossystem)

* second experiment:
  terminal 1:
  ```
  roslaunch turtlebot3_sim_tests test4.test
  ```
  terminal 2:
  ```
  rosrun rosgraph_monitor rossystem_snapshot
  ```
   result:
  [ turtlebot3_sim_tests/resources/turtlebot_nav.rossystem
  ](https://github.com/ipa-rwu/araig_test_stack/blob/095fca1aa9d7ad7babb14a6f4b56a303f5fd77bb/turtlebot3_sim_tests/resources/test4.rossystem)

**Comment by NadiaHG** [comment]
@ipa-rwu could you please specify where is the resulted file wrong?

the snapshot **HAS** to generate together with the .rossystem file a dump.ros file, otherwise you will miss the definition of the interfaces. See https://github.com/ipa-nhg/ros-model-experiments/tree/master/cob4-25/cob4-25_runtime/rosnodes from the experiments done with the previous version ->  `ros_graph_parser` https://github.com/ipa320/ros_graph_parser/blob/master/src/ros_graph_parser/snapshot.py#L116

@ipa-hsd can you please check this?

**Comment by hsd-dev** [comment]
@ipa-nhg currently I am not generating a .ros file. I will have to add that implementation.

**Comment by ipa-rwu** [comment]
Sorry, rossystem file is right. It was because of the missing .ros file. 
I did a fix in [ros_graph_parser](https://github.com/ipa-rwu/ros_graph_parser/tree/rwu/fix%2Fadd-service) and it can create a dump.ros. 
The result is as shown in https://github.com/ipa-rwu/araig_test_stack/pull/43/commits/926337e09e747c9b7aa279a80b163ee52e2e3865 .
Then I updated dump.ros to current .ros format, as shown in here https://github.com/ipa-rwu/araig_test_stack/pull/43/commits/c00f87a1fe472cc03838b5870e9fabd0efc262b3 .
Then I didn't get errors in eclipse

**Comment by NadiaHG** [comment]
@ipa-rwu thanks for your changes! can you please open a PR with the dump.ros generator?

**Comment by hsd-dev** [comment]
I would prefer to add that implementation to `ros_model_parser` instead of `ros_graph_parser`. I will send a PR soon. This is the generated .ros
```
PackageSet {
  CatkinPackage my_ros_pkg {
    Artifact test {
      Node { name /turtlesim
        Publishers {
          Publisher { name '/turtle1/color_sensor' message 'turtlesim.Color'},
          Publisher { name '/turtle1/pose' message 'turtlesim.Pose'}}}
}}}
```

**Comment by ipa-rwu** [comment]
@ipa-hsd The point of my view is that if I want to use ros-tooling for an existing application, I want to have .ros and .rossystem together.

**Comment by NadiaHG** [comment]
@ipa-nhg both files will be generated together. The ros_model_parser, that @ipa-hsd pointed, is the python module that implements the python API for the metamodels, and rosgraph_monitor software depend on it to avoid duplicate code and have to update a single piece of code for each change of the model. 

Looking to: https://github.com/ipa-rwu/araig_test_stack/commit/c00f87a1fe472cc03838b5870e9fabd0efc262b3 I think you used the old implementation, this grammar is old and not supported by the latest version of the tooling (see comment: https://github.com/ipa320/ros-model/releases/tag/1.5.0 )

Please if you made changes of the code, open PRs and we can discuss there the changes.

**Comment by hsd-dev** [comment]
@ipa-nhg @ipa-rwu please check https://github.com/ipa320/rosgraph_monitor/pull/14 and https://github.com/ipa320/ros_model_parser/pull/21. The test.ros is
```
PackageSet {
  CatkinPackage my_ros_pkg {
    Artifact test {
      Node { name /turtlesim
        ServiceServers {
          ServiceServer { name '/kill' service 'turtlesim.Kill'},
          ServiceServer { name '/spawn' service 'turtlesim.Spawn'},
          ServiceServer { name '/turtle1/set_pen' service 'turtlesim.SetPen'},
          ServiceServer { name '/reset' service 'std_srvs.Empty'},
          ServiceServer { name '/turtle1/teleport_relative' service 'turtlesim.TeleportRelative'},
          ServiceServer { name '/turtle1/teleport_absolute' service 'turtlesim.TeleportAbsolute'},
          ServiceServer { name '/clear' service 'std_srvs.Empty'}}
        Publishers {
          Publisher { name '/turtle1/pose' message 'turtlesim.Pose'},
          Publisher { name '/turtle1/color_sensor' message 'turtlesim.Color'}}
        Subscribers {
          Subscriber { name '/turtle1/cmd_vel' message 'geometry_msgs.Twist'}}
        Parameters {
          Parameter { name '/turtlesim/background_g' type Integer {default 86}},
          Parameter { name '/turtlesim/background_b' type Integer {default 255}},
          Parameter { name '/turtlesim/background_r' type Integer {default 69}}}}
}}}
``` 
and the corresponding test.rossystem is
```
RosSystem { Name 'demo'
    RosComponents ( 

        ComponentInterface { name '/turtlesim'
            RosParameters {
                RosParameter '/turtlesim/background_b' {RefParameter './turtlesim./turtlesim./turtlesim/background_b' value 255},
                RosParameter '/turtlesim/background_g' {RefParameter './turtlesim./turtlesim./turtlesim/background_g' value 86},
                RosParameter '/turtlesim/background_r' {RefParameter './turtlesim./turtlesim./turtlesim/background_r' value 69}}
            RosPublishers {
                RosPublisher '/turtle1/pose' {RefPublisher './turtlesim./turtlesim./turtle1/pose'},
                RosPublisher '/turtle1/color_sensor' {RefPublisher './turtlesim./turtlesim./turtle1/color_sensor'}}
            RosSubscribers {
                RosSubscriber '/turtle1/cmd_vel' {RefSubscriber './turtlesim./turtlesim./turtle1/cmd_vel'}}
            RosSrvServers {
                RosServiceServer '/turtle1/teleport_absolute' {RefServer './turtlesim./turtlesim./turtle1/teleport_absolute'},
                RosServiceServer '/turtle1/set_pen' {RefServer './turtlesim./turtlesim./turtle1/set_pen'},
                RosServiceServer '/clear' {RefServer './turtlesim./turtlesim./clear'},
                RosServiceServer '/kill' {RefServer './turtlesim./turtlesim./kill'},
                RosServiceServer '/turtle1/teleport_relative' {RefServer './turtlesim./turtlesim./turtle1/teleport_relative'},
                RosServiceServer '/spawn' {RefServer './turtlesim./turtlesim./spawn'},
                RosServiceServer '/reset' {RefServer './turtlesim./turtlesim./reset'}}
        }
)
}
```

**Comment by hsd-dev** [comment]
@ipa-rwu I tried your example and looks like it fails for parameters of type `list`. [Here](https://github.com/ipa320/ros_model_parser/blob/bc10e4d0dc55770fae875dcb1c8a5035df1e47b2/scripts/generators/ros_system_model_generator_example.py#L43) I changed to 
```
'global_parameters' : {'/dummy_param' : [['runner', 'interpreters', 'calculators'], 'list']}}
```
and I get the error
```
get_type() missing 2 required positional arguments: 'default' and 'given_type'
```
https://github.com/ipa320/ros_model_parser/pull/21/commits/8335b1150af029e83b629fe08f823643b2a0bca6 fixed for me
