### ISSUE TITLE
Add a new function to generate a ros and a rossystem file from the data obtained from the rosgraph analysis

### ISSUE THREAD

**Issue by NadiaHG** [ipa320/rosgraph_monitor#4]
We need a way to extract automatically the models from a running system. For the previous version this was done by the ros_graph_parser, using the command:

`rosrun ros_graph_parser java_snapshot ros_model_file ros_system_file system_name package_name`

(see: https://github.com/ipa-nhg/ros_graph_parser/tree/SoSymPaper#java)

We need an equivalent here. It can also be a service that get as input the path of the file and the name of the system and then the graph_observer  with dump the information obtained from:

https://github.com/ipa320/rosgraph_monitor/blob/ecf781b073c179d7ffaa455fd94dc8393b9747e4/src/rosgraph_monitor/observers/graph_observer.py#L86

to the desired .ros and .rossystem files

**Comment by hsd-dev** [comment]
Locally I have a file that I am using for testing
```
#!/usr/bin/env python3

import rospy
from ros_model_generator.rossystem_generator import RosSystemModelGenerator
from rosgraph_monitor.observers.graph_observer import create_ros_graph_snapshot

def generate_model_from_snapshot():
    components = create_ros_graph_snapshot()
    generator = RosSystemModelGenerator('demo')
    try:
        generator.create_ros_system_model_list(components, <path/to/file/test.rossystem>)
    except Exception as e:
        print(e.args)

if __name__ == "__main__":
    rospy.init_node('dummy_node')
    generate_model_from_snapshot()
```
I can push that as a separate node.

**Comment by hsd-dev** [comment]
See: https://github.com/ipa320/rosgraph_monitor/pull/1/commits/6d5680e946c867c31ab8f606fcd2bb83c03f78c4

**Comment by NadiaHG** [comment]
perfect! this script is enough. Can you please update the README of the repository to add this function?

**Comment by hsd-dev** [comment]
See https://github.com/ipa320/rosgraph_monitor/pull/1/commits/8a7baa386f1d65a1433f71e639f6cf329e7a74ed

**Comment by hsd-dev** [comment]
`rossystem` was generated from the snapshot in https://github.com/ipa320/rosgraph_monitor/pull/1. `ros` is being handled in https://github.com/ipa320/rosgraph_monitor/pull/14
